### PR TITLE
python3: Build fix for Apple LLVM 4.2 on 10.7

### LINKED ISSUE #1294: Python3 fails to build on Lion
`Brew install -vd Python3` fails, here is output
`clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic 
-DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused
-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-
function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include 
-I/usr/local/opt/tcl-tk/include -I/usr/local/opt/tcl-tk/include  -DPy_BUILD_CORE
_BUILTIN  -DPy_BUILD_CORE_BUILTIN -I./Include/internal -c ./Modules/signalmodule
.c -o Modules/signalmodule.o
fatal error: error in backend: Cannot select: 0x102565410: i8,ch = AtomicLoad 0x
101ae45a0, 0x102565110<Volatile LD1[@is_tripped.0.b]> [ID=11]
  0x102565110: i64 = X86ISD::WrapperRIP 0x102565810 [ID=10]
    0x102565810: i64 = TargetGlobalAddress<i1* @is_tripped.0.b> 0 [ID=8]
In function: _PyErr_CheckSignalsTstate
make: *** [Modules/signalmodule.o] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Formula
Path: /usr/local/Library/Formula/python3.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia904500.us.archive.org/24/items/tigerbrew
CPU: dual-core 64-bit penryn
OS X: 10.7.5-x86_64
Curl: /usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.6.5 => /opt/X11
System Ruby: 2.3.3-222 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3
/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/us
r/bin/ruby
Java: 1.6.0_65-b14-462
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CPPFLAGS: -I/usr/local/opt/tcl-tk/include
LDFLAGS: -L/usr/local/opt/tcl-tk/lib
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/
gettext:/usr/local/opt/perl:/usr/local/opt/openssl3:/usr/local/opt/bzip2:/usr/lo
cal/opt/zlib:/usr/local/opt/tcl-tk:/usr/local/opt/libffi:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.frame
work/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current
/Libraries
PKG_CONFIG_PATH: /usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/readline/lib/pkg
config:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/openssl3/lib/pkgconfig
:/usr/local/opt/bzip2/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local
/opt/tcl-tk/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.7
ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/xz/bin:/usr/local/opt/pkg-config
/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/gettext/bi
n:/usr/local/opt/perl/bin:/usr/local/opt/openssl3/bin:/usr/local/opt/bzip2/bin:/
usr/local/opt/tcl-tk/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: python3 3.10.16 did not build
Logs:
     /Users/Mylogin/Library/Logs/Homebrew/python3/01.configure
     /Users/Mylogin/Library/Logs/Homebrew/python3/01.configure.cc
     /Users/Mylogin/Library/Logs/Homebrew/python3/02.make
     /Users/Mylogin/Library/Logs/Homebrew/python3/02.make.cc
     /Users/Mylogin/Library/Logs/Homebrew/python3/config.log

/usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/net/http.r
b:933:in `connect_nonblock': Failed to connect to: https://api.github.com/search
/issues?q=python3+repo:mistydemeo/tigerbrew+in:title+state:open&per_page=100 (Gi
tHub::Error)
SSL_connect returned=1 errno=0 state=error: certificate verify failed
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/net/http.rb:933:in `connect'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/net/http.rb:863:in `do_start'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/net/http.rb:852:in `start'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:319:in `open_http'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:737:in `buffer_open'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:212:in `block in open_loop'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:210:in `catch'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:210:in `open_loop'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:151:in `open_uri'
        from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:717:in `open'
   from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3
.0/open-uri.rb:31:in `open'
        from /usr/local/Library/Homebrew/utils.rb:435:in `open'
        from /usr/local/Library/Homebrew/utils.rb:465:in `issues_matching'
        from /usr/local/Library/Homebrew/utils.rb:497:in `issues_for_formula'
        from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
        from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
        from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
        from /usr/local/Library/brew.rb:170:in `rescue in <main>'
        from /usr/local/Library/brew.rb:61:in `<main>'`

Any idea on how to solve this?

### PR DESCRIPTION
**Pull request by sevan**
Support for atomics is buggy and causes of backend failure in compiler.
In Apple LLVM 4.1 __atomic_load_n & __atomic_store_n were not implemented
so there was not an issue but with the command line tools from
Xcode 4.6.2 these functions are present & the build tries to make use
of them & fails.

fails:
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix

lacks support:
Apple clang version 4.1 (tags/Apple/clang-421.11.66) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix

Patch via Macports.

Tested on Lion with Command line tools from Xcode 4.6.2  (xcode462_cltools_10_76938260a.dmg)
Resolves #1294

### CODE REVIEW

File: Library/Formula/python3.rb [hunk 1]
```diff
@@ -77,8 +80,6 @@ def install
       --with-system-ffi
     ]
 
-    args << "--without-gcc" if ENV.compiler == :clang
```
Comment (mistydemeo) [inline Library/Formula/python3.rb:80]: Hm, is this no longer needed?

Comment (sevan) [reply Library/Formula/python3.rb:80]: Doesn't appear to be.
Saw this fly by during a build:
`configure: WARNING: unrecognized options: --without-gcc`

Comment (mistydemeo) [reply Library/Formula/python3.rb:80]: OK, yup - looks like it went away in python 3.9.0: https://bugs.python.org/issue33483
