### PR TITLE
rsync: Add formula for v3.2.7

### LINKED ISSUE #791: rsync failed to build on 10.4
https://gist.github.com/happy-dreame/aaf49c4387dd4e0bb188b058aa97bcf6

Thank you.

### PR DESCRIPTION
**Pull request by sevan**
Adapted from
https://github.com/Homebrew/homebrew-core/blob/a76c6520515986d4c77bab61cab99076bcc2b727/Formula/rsync.rb

Resolves #791 
Need PR #825 to build, and ideally #824

### CODE REVIEW

File: Library/Formula/rsync.rb [hunk 1]
```diff
@@ -0,0 +1,1385 @@
...
+  depends_on "lz4"
+  depends_on "openssl"
+  depends_on "popt"
+  depends_on "xxhash"
+  depends_on "zlib"
+
+  def install
+    ENV.append_to_cflags "-DSUPPORT_FILEFLAGS"
+    args = %W[
+      --prefix=#{HOMEBREW_PREFIX}
```
Comment (mistydemeo) [inline Library/Formula/rsync.rb:19]: Can you make this `prefix` instead? This is installing rsync in a way where it's not being managed by Tigerbrew. Unfortunately we don't have the sandboxing setup to actively prevent that right now.

**Review by mistydemeo — CHANGES_REQUESTED** [review]

File: Library/Formula/rsync.rb (hunk 1 above)
Comment (sevan) [reply Library/Formula/rsync.rb]: Sure, don.

**Review by mistydemeo — APPROVED** [review]
Thank you!
